### ISSUE TITLE
Won't work with new Quest PDF's

### ISSUE THREAD

**Issue by descrip** [abdallaharar/autogpa-uwaterloo#1]
The new Quest update gives your transcripts as PDF's instead of the web page, any workaround?

**Comment by abdallaharar** [comment]
Unfortunately no workaround for this as this would require a total redesign of this project. Quest's new transcript seems to block you from easily copying the contents, which essentially defeats the simplicity of this tool. I guess I will have to let it die for now; feel free the carry the torch and make a new one supporting PDF upload 😃.
