### ISSUE TITLE
Didnt Work After Quest is Updated 

### ISSUE THREAD

**Issue by zhwang0** [abdallaharar/autogpa-uwaterloo#2]
After Quest is updated, the unofficial transcript is shown as .pdf. Cannot directly copy-paste anymore.

**Comment by nakulpathak3** [comment]
same issue^

**Comment by GeraldNDA** [comment]
Check this out: https://codepen.io/GeraldNDA/full/VxpKWb

**Comment by zhwang0** [comment]
Already graduated! Good luck, your guys!

**Comment by GeraldNDA** [comment]
lol also as an FYI, this one exists https://www.wa-transcript.com
